services:
  mc:
    image: itzg/minecraft-server:java21-graalvm
    ports:
      - 25565:25565
    environment:
      EULA: TRUE
      # server type
      TYPE: FABRIC
      VERSION: 1.21
      MOD_PLATFORM: MODRINTH
      MODRINTH_MODPACK: nitroserver
      MODS: |
        https://cdn.modrinth.com/data/rbJ7eS5V/versions/I3kp6jxL/dcintegration-fabric-3.0.7.2-1.21.jar
        https://cdn.modrinth.com/data/gvQqBUqZ/versions/NTZCh7rb/lithium-fabric-mc1.21-0.13.0.jar
        https://cdn.modrinth.com/data/YS3ZignI/versions/dbmmgocV/tt20-0.7.0%2Bmc1.21.jar
      REPLACE_ENV_DURING_SYNC: true
      # server settings
      DIFFICULTY: normal
      MAX_PLAYERS: 10
      VIEW_DISTANCE: 16
      SPAWN_PROTECTION: 0
      SERVER_NAME: turtle
      MOTD: turtles are cute uwu
      OPS: rayzr
      ICON: https://i1.sndcdn.com/artworks-000203139607-k96me5-t500x500.jpg
      # fine-tuning
      MEMORY: 2G
      USE_AIKAR_FLAGS: true
      UID: ${UID:?missing}
      GID: ${GID:?missing}
      CFG_DISCORD_TOKEN: ${CFG_DISCORD_TOKEN?missing}
      CFG_DISCORD_CHANNEL: ${CFG_DISCORD_CHANNEL?missing}
      CFG_DISCORD_ADMIN_ROLE: ${CFG_DISCORD_ADMIN_ROLE?missing}
    volumes:
      - ./data:/data
      - ./config:/config
      - ./mods:/mods
    tty: true
    stdin_open: true
    restart: unless-stopped
  bot:
    image: turtle-server/bot
    build: ./bot
    env_file: ./bot/.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
