services:
  mc:
    image: itzg/minecraft-server:stable
    ports:
      - 25565:25565
    environment:
      EULA: TRUE
      # server type
      TYPE: FABRIC
      VERSION: 1.21.5
      MODS: |
        https://cdn.modrinth.com/data/P7dR8mSH/versions/SQv5lrom/fabric-api-0.124.2%2B1.21.5.jar
        https://cdn.modrinth.com/data/gvQqBUqZ/versions/VWYoZjBF/lithium-fabric-0.16.2%2Bmc1.21.5.jar
        https://cdn.modrinth.com/data/VSNURh3q/versions/jrmtD6AF/c2me-fabric-mc1.21.5-0.3.3.0.0.jar
        https://cdn.modrinth.com/data/KuNKN7d2/versions/sUh67T4Y/noisium-fabric-2.6.0%2Bmc1.21.5.jar
        https://cdn.modrinth.com/data/uXXizFIs/versions/CtMpt7Jr/ferritecore-8.0.0-fabric.jar
        https://cdn.modrinth.com/data/fQEb0iXm/versions/neW85eWt/krypton-0.2.9.jar
        https://cdn.modrinth.com/data/4WWQxlQP/versions/TeMECVcw/servercore-fabric-1.5.11%2B1.21.5.jar
        https://cdn.modrinth.com/data/l6YH9Als/versions/NURCAL12/spark-1.10.128-fabric.jar
        https://cdn.modrinth.com/data/rbJ7eS5V/versions/E9rMiAL6/dcintegration-fabric-MC1.21.5-3.1.0.1.jar
        https://cdn.modrinth.com/data/uCdwusMi/versions/Mt9bDAs6/DistantHorizons-neoforge-fabric-2.3.2-b-1.21.5.jar
      REPLACE_ENV_DURING_SYNC: true
      # server settings
      DIFFICULTY: normal
      MAX_PLAYERS: 10
      SPAWN_PROTECTION: 0
      SERVER_NAME: turtle
      MOTD: turtles are cute uwu
      OPS: rayzr
      ICON: https://i1.sndcdn.com/artworks-000203139607-k96me5-t500x500.jpg
      # fine-tuning
      MEMORY: 2G
      USE_AIKAR_FLAGS: true
      UID: ${UID:?missing}
      GID: ${GID:?missing}
      CFG_DISCORD_TOKEN: ${CFG_DISCORD_TOKEN:-xxx}
      CFG_DISCORD_CHANNEL: ${CFG_DISCORD_CHANNEL:-0}
      CFG_DISCORD_ADMIN_ROLE: ${CFG_DISCORD_ADMIN_ROLE:-0}
      CFG_DISCORD_SERVER_URL: ${CFG_DISCORD_SERVER_URL:-mc.example.com}
    volumes:
      - ./data:/data
      - ./config:/config
    tty: true
    stdin_open: true
    restart: unless-stopped
