services:
  mc:
    image: itzg/minecraft-server:stable
    ports:
      - 25565:25565
    environment:
      EULA: TRUE
      # server type
      TYPE: FABRIC
      VERSION: 1.21.1
      MODS: |
        https://cdn.modrinth.com/data/P7dR8mSH/versions/4AkOEqGy/fabric-api-0.115.6%2B1.21.1.jar
        https://cdn.modrinth.com/data/gvQqBUqZ/versions/MM5BBBOK/lithium-fabric-0.15.0%2Bmc1.21.1.jar
        https://cdn.modrinth.com/data/VSNURh3q/versions/ysBifeyb/c2me-fabric-mc1.21.1-0.3.0%2Balpha.0.319.jar
        https://cdn.modrinth.com/data/KuNKN7d2/versions/4sGQgiu2/noisium-fabric-2.3.0%2Bmc1.21-1.21.1.jar
        https://cdn.modrinth.com/data/uXXizFIs/versions/bwKMSBhn/ferritecore-7.0.2-hotfix-fabric.jar
        https://cdn.modrinth.com/data/fQEb0iXm/versions/Acz3ttTp/krypton-0.2.8.jar
        https://cdn.modrinth.com/data/4WWQxlQP/versions/FDzBkBBD/servercore-fabric-1.5.10%2B1.21.1.jar
        https://cdn.modrinth.com/data/l6YH9Als/versions/cALUj9l1/spark-1.10.109-fabric.jar
        https://cdn.modrinth.com/data/cUhi3iB2/versions/XxA9k8Fb/tabtps-fabric-mc1.21.1-1.3.25.jar
        https://cdn.modrinth.com/data/rbJ7eS5V/versions/I3kp6jxL/dcintegration-fabric-3.0.7.2-1.21.jar
        https://cdn.modrinth.com/data/uCdwusMi/versions/jkSxZOJh/DistantHorizons-neoforge-fabric-2.3.2-b-1.21.1.jar
      REPLACE_ENV_DURING_SYNC: true
      # server settings
      DIFFICULTY: normal
      MAX_PLAYERS: 10
      SPAWN_PROTECTION: 0
      SERVER_NAME: turtle
      MOTD: turtles are cute uwu
      OPS: rayzr
      ICON: https://i1.sndcdn.com/artworks-000203139607-k96me5-t500x500.jpg
      # fine-tuning
      MEMORY: 2G
      USE_AIKAR_FLAGS: true
      UID: ${UID:?missing}
      GID: ${GID:?missing}
      CFG_DISCORD_TOKEN: ${CFG_DISCORD_TOKEN:-xxx}
      CFG_DISCORD_CHANNEL: ${CFG_DISCORD_CHANNEL:-0}
      CFG_DISCORD_ADMIN_ROLE: ${CFG_DISCORD_ADMIN_ROLE:-0}
      CFG_DISCORD_SERVER_URL: ${CFG_DISCORD_SERVER_URL:-mc.example.com}
    volumes:
      - ./data:/data
      - ./config:/config
    tty: true
    stdin_open: true
    restart: unless-stopped
