services:
  mc:
    image: itzg/minecraft-server:java21-graalvm
    ports:
      - 25565:25565
    environment:
      EULA: TRUE
      # server type
      TYPE: FABRIC
      VERSION: 1.21
      MOD_PLATFORM: MODRINTH
      MODRINTH_MODPACK: nitroserver
      # server settings
      DIFFICULTY: normal
      MAX_PLAYERS: 10
      VIEW_DISTANCE: 16
      SERVER_NAME: turtle
      MOTD: turtles are cute uwu
      OPS: rayzr
      ICON: https://images.emojiterra.com/google/noto-emoji/unicode-15.1/color/svg/1f422.svg
      # fine-tuning
      MEMORY: 2G
      USE_AIKAR_FLAGS: true
      UID: ${UID:?missing}
      GID: ${GID:?missing}
    volumes:
      - ./data:/data
      - ./mods:/mods
    tty: true
    stdin_open: true
    restart: unless-stopped
  bot:
    image: turtle-server/bot
    build: ./bot
    env_file: ./bot/.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
